"""Initial migration.

Revision ID: 311d40d3b935
Revises: 
Create Date: 2025-05-27 14:53:18.472450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311d40d3b935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('engine_size')

    # ### end Alembic commands ###
